apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "acs.worker.name" . }}
  labels:
    {{- include "acs.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  {{- if not .Values.worker.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount.worker }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "acs.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        {{- include "acs.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "acs.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      
      containers:
        - name: worker
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.app.repository }}:{{ .Values.image.app.tag }}"
          imagePullPolicy: {{ .Values.image.app.pullPolicy }}
          command:
            - php
            - artisan
            - queue:work
            - --sleep=3
            - --tries=3
            - --timeout=120
            - --max-jobs=1000
            - --max-time=3600
          env:
            {{- include "acs.env" . | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "acs.fullname" . }}-config
            - secretRef:
                name: {{ include "acs.fullname" . }}-secret
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          volumeMounts:
            - name: app-storage
              mountPath: /var/www/html/storage/app
      
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: {{ include "acs.fullname" . }}-storage
      
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
