apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "acs.fullname" . }}-storage
  labels:
    {{- include "acs.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany  # Required for multi-pod access
  storageClassName: {{ .Values.persistence.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.storage.size }}
